version: '3.9'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    networks:
      - back-network
    ports:
      - "3306:3306"  # Expondo a porta 3306 do MySQL

  api:
    build: .
    command: >
      sh -c "
      sleep 30 &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - back-network 

networks:
  back-network:
    driver: bridge

volumes:
  db_data:
